version: "3.1"
services:
  mongo-db:
    image: mongo
    restart: always
    # ports:
    #   - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-root-dev-user
      MONGO_INITDB_ROOT_PASSWORD: mongo-root-dev-pass
    networks:
      - mevn-app-network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo-admin-dev-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo-admin-dev-pass
      ME_CONFIG_MONGODB_URL: mongodb://mongo-root-dev-user:mongo-root-dev-pass@mongo-db:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - mevn-app-network
  mevn-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mevn-app
    container_name: mevn-app
    restart: always
    ports:
      - 3001:3001
      - 3000:3000
    environment:
      - NODE_ENV=development
      - DB_URL=mongodb://mongo-root-dev-user:mongo-root-dev-pass@mongo-db:27017/admin
    networks:
      - mevn-app-network
    depends_on:
      - mongo-db
networks:
  mevn-app-network:
    driver: bridge


